(function () {
  "use strict";
  const $=id=>document.getElementById(id),DRAFT_KEY="drawHeroCreatorDraftV1",SAVE_KEY="drawHeroSaveV1";
  let pack=loadDraft(),editingStage=null,editingQuestion=null,templateBoard=null;

  function blankPack(){return{schema:"draw-hero-content-pack",schemaVersion:1,id:`pack_${Date.now()}`,name:"ชุดฝึกเขียนของฉัน",author:"คุณครู",version:"1.0.0",description:"Content Pack สำหรับ DRAW HERO",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),questions:[],stages:[],templates:{}};}
  function loadDraft(){try{const parsed=JSON.parse(localStorage.getItem(DRAFT_KEY));return validatePack(parsed).valid?parsed:blankPack();}catch(error){return blankPack();}}
  function persist(message){pack.updatedAt=new Date().toISOString();try{localStorage.setItem(DRAFT_KEY,JSON.stringify(pack));syncToGameSave();}catch(error){status("พื้นที่จัดเก็บเต็ม กรุณา Export สำรอง",false);return;}status(message||"บันทึกในเครื่องแล้ว",true);renderAll();}
  function syncToGameSave(){try{const save=JSON.parse(localStorage.getItem(SAVE_KEY)||"{}");save.customPacks=Array.isArray(save.customPacks)?save.customPacks:[];const index=save.customPacks.findIndex(item=>item.id===pack.id);if(index>=0)save.customPacks[index]=pack;else save.customPacks.push(pack);localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch(error){/* The creator still works if game save is unavailable. */}}
  function status(text,good){const node=$("creator-status");node.textContent=`${good===false?"●":"●"} ${text}`;node.style.color=good===false?"#ff8895":"#55c271";}
  function uid(prefix){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,6)}`;}
  function num(id,fallback){const value=Number($(id).value);return Number.isFinite(value)?value:fallback;}
  function selectedValues(select){return Array.from(select.selectedOptions).map(option=>option.value);}
  function stageFromForm(){
    const questionIds=selectedValues($("stage-questions"));
    return{id:editingStage||uid("stage"),name:$("stage-name").value.trim(),description:$("stage-description").value.trim(),world:num("stage-world",1),level:pack.stages.length+1,contentType:$("stage-content-type").value,language:$("stage-language").value,difficulty:$("stage-difficulty").value,timeLimit:num("stage-time",9),enemySpeed:num("stage-speed",1),enemyTypes:[$("stage-enemy").value],enemyCount:num("stage-enemy-count",5),questions:questionIds,rewardXP:num("stage-xp",50),rewardCoins:num("stage-coins",20),guideMode:$("stage-guide").value,recognitionThreshold:num("stage-threshold",55),boss:$("stage-boss").value==="true"};
  }
  function questionFromForm(){const display=$("question-display").value.trim(),answer=$("question-answer").value.trim();return{id:editingQuestion||uid("question"),type:$("question-type").value,language:$("question-language").value,display,answer,difficulty:$("question-difficulty").value,guideMode:$("question-guide").value,recognitionMode:$("question-recognition").value,threshold:num("question-threshold",55),timeLimit:num("question-time",9),hint:$("question-hint").value.trim(),reward:num("question-reward",100)};}
  function saveStage(event){event.preventDefault();const stage=stageFromForm();if(!stage.name){status("กรุณาระบุชื่อด่าน",false);return;}if(!stage.questions.length){status("กรุณาเลือกคำถามอย่างน้อย 1 ข้อ",false);return;}const index=pack.stages.findIndex(item=>item.id===stage.id);if(index>=0)pack.stages[index]=stage;else pack.stages.push(stage);editingStage=null;clearStageForm(false);persist("บันทึกด่านแล้ว");showPanel("stage-manager");}
  function saveQuestion(event){event.preventDefault();const question=questionFromForm();if(!question.display||!question.answer){status("กรุณากรอกโจทย์และคำตอบ",false);return;}const index=pack.questions.findIndex(item=>item.id===question.id);if(index>=0)pack.questions[index]=question;else pack.questions.push(question);editingQuestion=null;clearQuestionForm();persist("เพิ่มคำถามแล้ว");showPanel("question-manager");}
  function clearStageForm(clearValues=true){editingStage=null;if(clearValues)$("stage-form").reset();$("stage-name").value=clearValues?"ด่านฝึกเวทของฉัน":$("stage-name").value;Array.from($("stage-questions").options).forEach(option=>option.selected=false);}
  function clearQuestionForm(){$("question-form").reset();editingQuestion=null;previewQuestion();}
  function editStage(id){const stage=pack.stages.find(item=>item.id===id);if(!stage)return;editingStage=id;$("stage-name").value=stage.name;$("stage-description").value=stage.description||"";$("stage-world").value=stage.world;$("stage-content-type").value=stage.contentType;$("stage-language").value=stage.language||"mixed";$("stage-difficulty").value=stage.difficulty;$("stage-time").value=stage.timeLimit;$("stage-speed").value=stage.enemySpeed;$("stage-enemy").value=(stage.enemyTypes||["goblin"])[0];$("stage-enemy-count").value=stage.enemyCount||stage.questions.length;$("stage-xp").value=stage.rewardXP;$("stage-coins").value=stage.rewardCoins;$("stage-guide").value=stage.guideMode;$("stage-threshold").value=stage.recognitionThreshold;$("stage-boss").value=String(!!stage.boss);Array.from($("stage-questions").options).forEach(option=>option.selected=stage.questions.includes(option.value));showPanel("stage-editor");}
  function editQuestion(id){const q=pack.questions.find(item=>item.id===id);if(!q)return;editingQuestion=id;$("question-display").value=q.display;$("question-answer").value=q.answer;$("question-language").value=q.language;$("question-type").value=q.type;$("question-hint").value=q.hint||"";$("question-difficulty").value=q.difficulty;$("question-time").value=q.timeLimit;$("question-recognition").value=q.recognitionMode;$("question-guide").value=q.guideMode;$("question-threshold").value=q.threshold;$("question-reward").value=q.reward||100;previewQuestion();showPanel("question-editor");}
  function removeStage(id){if(!confirm("ลบด่านนี้ออกจาก Content Pack หรือไม่?"))return;pack.stages=pack.stages.filter(item=>item.id!==id);persist("ลบด่านแล้ว");}
  function removeQuestion(id){if(!confirm("ลบคำถามนี้หรือไม่? คำถามจะถูกนำออกจากทุกด่านด้วย"))return;pack.questions=pack.questions.filter(item=>item.id!==id);pack.stages.forEach(stage=>{stage.questions=stage.questions.filter(questionId=>questionId!==id);});persist("ลบคำถามแล้ว");}
  function renderAll(){renderQuestionOptions();renderStageTable();renderQuestionTable();renderSummary();renderValidation();fillPackForm();updateTemplateCount();}
  function renderQuestionOptions(){const select=$("stage-questions"),selected=selectedValues(select);select.innerHTML="";pack.questions.forEach(q=>{const option=document.createElement("option");option.value=q.id;option.textContent=`${q.display} → ${q.answer} (${q.type})`;option.selected=selected.includes(q.id);select.appendChild(option);});}
  function renderStageTable(){const body=$("stage-table-body");body.innerHTML="";if(!pack.stages.length){body.innerHTML='<tr><td colspan="5">ยังไม่มีด่าน — เริ่มสร้างด่านแรกได้เลย</td></tr>';return;}pack.stages.forEach(stage=>{const row=document.createElement("tr");row.innerHTML=`<td>${safe(stage.name)}</td><td>${safe(stage.contentType)}</td><td>${safe(stage.difficulty)}</td><td>${stage.questions.length}</td><td><button class="mini-button edit">✎</button> <button class="mini-button preview">▶</button> <button class="mini-button delete">×</button></td>`;row.querySelector(".edit").addEventListener("click",()=>editStage(stage.id));row.querySelector(".preview").addEventListener("click",()=>previewStage(stage.id));row.querySelector(".delete").addEventListener("click",()=>removeStage(stage.id));body.appendChild(row);});}
  function renderQuestionTable(){const body=$("question-table-body");body.innerHTML="";if(!pack.questions.length){body.innerHTML='<tr><td colspan="5">ยังไม่มีคำถาม</td></tr>';return;}pack.questions.forEach(q=>{const row=document.createElement("tr");row.innerHTML=`<td>${safe(q.display)}</td><td>${safe(q.answer)}</td><td>${safe(q.type)}</td><td>${q.threshold}%</td><td><button class="mini-button edit">✎</button> <button class="mini-button delete">×</button></td>`;row.querySelector(".edit").addEventListener("click",()=>editQuestion(q.id));row.querySelector(".delete").addEventListener("click",()=>removeQuestion(q.id));body.appendChild(row);});}
  function safe(value){const node=document.createElement("span");node.textContent=String(value||"");return node.innerHTML;}
  function renderSummary(){$("summary-stages").textContent=pack.stages.length;$("summary-questions").textContent=pack.questions.length;$("summary-templates").textContent=Object.values(pack.templates||{}).reduce((sum,items)=>sum+items.length,0);}
  function fillPackForm(){$("pack-name").value=pack.name||"";$("pack-author").value=pack.author||"";$("pack-version").value=pack.version||"1.0.0";$("pack-description").value=pack.description||"";}
  function savePackInfo(event){event.preventDefault();pack.name=$("pack-name").value.trim();pack.author=$("pack-author").value.trim();pack.version=$("pack-version").value.trim();pack.description=$("pack-description").value.trim();persist("บันทึกข้อมูล Pack แล้ว");}
  function newPack(){if(!confirm("สร้าง Pack ใหม่หรือไม่? โปรด Export Pack เดิมก่อนหากต้องการเก็บไว้"))return;pack=blankPack();editingStage=null;editingQuestion=null;persist("สร้าง Content Pack ใหม่แล้ว");showPanel("pack-editor");}
  function validatePack(data){const errors=[];if(!data||typeof data!=="object")errors.push("รูปแบบไฟล์ไม่ใช่ Object");if(data&&data.schema!=="draw-hero-content-pack")errors.push("ไม่พบ schema ของ DRAW HERO");if(data&&!Array.isArray(data.questions))errors.push("questions ต้องเป็น Array");if(data&&!Array.isArray(data.stages))errors.push("stages ต้องเป็น Array");const ids=new Set();if(data&&Array.isArray(data.questions)){data.questions.forEach((q,i)=>{if(!q.id||!q.answer||!q.display)errors.push(`คำถามลำดับ ${i+1} ข้อมูลไม่ครบ`);if(q.id)ids.add(q.id);});}if(data&&Array.isArray(data.stages)){data.stages.forEach((s,i)=>{if(!s.id||!s.name||!Array.isArray(s.questions))errors.push(`ด่านลำดับ ${i+1} ข้อมูลไม่ครบ`);else if(!s.questions.length)errors.push(`ด่าน “${s.name}” ยังไม่มีคำถาม`);else if(s.questions.some(id=>!ids.has(id)))errors.push(`ด่าน “${s.name}” อ้างถึงคำถามที่ไม่มีอยู่`);});}return{valid:errors.length===0,errors};}
  function renderValidation(){const node=$("pack-validation");if(!node)return;const result=validatePack(pack);node.className=`pack-validation ${result.valid?"ready":"needs-work"}`;node.innerHTML=result.valid?`<b>✓ พร้อมเผยแพร่</b><small>${pack.stages.length} ด่าน • ${pack.questions.length} คำถาม • ตรวจข้อมูลครบแล้ว</small>`:`<b>! ยังต้องแก้ ${result.errors.length} จุด</b><small>${safe(result.errors.slice(0,2).join(" • "))}</small>`;}
  function importFile(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);const validation=validatePack(data);if(!validation.valid)throw new Error(validation.errors.join(" • "));pack=data;pack.templates=pack.templates||{};persist("Import Content Pack สำเร็จ");message("import-message",`นำเข้า “${pack.name}” แล้ว`,true);}catch(error){message("import-message",`ไฟล์ไม่ถูกต้อง: ${error.message}`,false);}event.target.value="";};reader.onerror=()=>message("import-message","ไม่สามารถอ่านไฟล์นี้ได้",false);reader.readAsText(file,"utf-8");}
  function message(id,text,good){const node=$(id);node.className=`validation-message ${good?"success":"error"}`;node.textContent=text;}
  function exportPack(){const validation=validatePack(pack);if(!validation.valid){message("export-message",validation.errors.join(" • "),false);return;}const blob=new Blob([JSON.stringify(pack,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${slug(pack.name)||"draw-hero-pack"}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);message("export-message","ดาวน์โหลด Content Pack แล้ว",true);}
  function slug(value){return String(value||"").toLowerCase().trim().replace(/[^a-z0-9ก-๙]+/g,"-").replace(/^-|-$/g,"");}
  async function copyJSON(){const text=JSON.stringify(pack,null,2);try{await navigator.clipboard.writeText(text);message("export-message","คัดลอก JSON แล้ว",true);}catch(error){const area=document.createElement("textarea");area.value=text;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove();message("export-message","คัดลอก JSON แล้ว",true);}}
  function encodePack(data){const bytes=new TextEncoder().encode(JSON.stringify(data));let binary="";bytes.forEach(byte=>{binary+=String.fromCharCode(byte);});return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
  function decodePack(value){const normalized=value.replace(/-/g,"+").replace(/_/g,"/");const binary=atob(normalized);const bytes=Uint8Array.from(binary,char=>char.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes));}
  async function copyShareLink(){const validation=validatePack(pack);if(!validation.valid){message("export-message",`ยังแชร์ไม่ได้: ${validation.errors[0]}`,false);return;}const encoded=encodePack(pack);if(encoded.length>12000){message("export-message","Pack มี Template ขนาดใหญ่ กรุณาแชร์ด้วยไฟล์ JSON",false);return;}const url=`${location.origin}${location.pathname}#pack=${encoded}`;try{await navigator.clipboard.writeText(url);message("export-message","คัดลอกลิงก์แชร์แล้ว ผู้รับเปิดลิงก์เพื่อนำเข้า Pack ได้ทันที",true);}catch(error){message("export-message","เบราว์เซอร์ไม่อนุญาตให้คัดลอก กรุณาใช้ Export JSON",false);}}
  function loadSharedPack(){const match=location.hash.match(/^#pack=(.+)$/);if(!match)return;try{const shared=decodePack(match[1]),validation=validatePack(shared);if(!validation.valid)throw new Error(validation.errors[0]);pack=shared;pack.templates=pack.templates||{};localStorage.setItem(DRAFT_KEY,JSON.stringify(pack));syncToGameSave();history.replaceState(null,"",location.pathname);status(`นำเข้า “${pack.name}” จากลิงก์แชร์แล้ว`,true);}catch(error){status(`ลิงก์แชร์ไม่ถูกต้อง: ${error.message}`,false);}}
  function previewStage(id){const stage=pack.stages.find(item=>item.id===id)||(editingStage?stageFromForm():pack.stages[0]);if(!stage){status("กรุณาสร้างและบันทึกด่านก่อน Preview",false);showPanel("stage-editor");return;}const questionIds=stage.questions||[];if(!questionIds.length){status("ด่านนี้ยังไม่มีคำถาม",false);return;}try{localStorage.setItem("drawHeroPreviewStage",JSON.stringify({stage,pack}));location.href="./index.html?preview=1";}catch(error){status("ไม่สามารถเตรียม Preview ได้",false);}}
  function previewQuestion(){try{$("question-preview").textContent=JSON.stringify(questionFromForm(),null,2);}catch(error){$("question-preview").textContent="{}";}}
  function initTemplateBoard(){templateBoard=new window.DrawHero.DrawingBoard($("template-canvas"));updateTemplateCount();}
  function saveTemplate(){const label=$("template-label").value.trim();if(!label){status("กรุณาระบุตัวอักษร",false);return;}if(!templateBoard.hasDrawing()){status("กรุณาวาดตัวอย่างก่อนบันทึก",false);return;}const canvas=templateBoard.exportInkCanvas();pack.templates[label]=pack.templates[label]||[];if(pack.templates[label].length>=5)pack.templates[label].shift();pack.templates[label].push(canvas.toDataURL("image/png"));templateBoard.clear();persist(`บันทึก Template “${label}” แล้ว`);updateTemplateCount();}
  function updateTemplateCount(){const label=$("template-label")?$("template-label").value.trim():"";const count=label&&pack.templates[label]?pack.templates[label].length:0;if($("template-sample-count"))$("template-sample-count").textContent=`${count} / 3`;}
  function showPanel(name){document.querySelectorAll(".creator-panel").forEach(panel=>panel.classList.toggle("active",panel.id===`panel-${name}`));document.querySelectorAll(".creator-nav [data-panel]").forEach(button=>button.classList.toggle("active",button.dataset.panel===name));const panel=$(`panel-${name}`);if(panel)$("creator-title").textContent=panel.dataset.title;window.scrollTo(0,0);}
  function bind(){
    document.querySelectorAll(".creator-nav [data-panel]").forEach(button=>button.addEventListener("click",()=>showPanel(button.dataset.panel)));
    $("stage-form").addEventListener("submit",saveStage);$("question-form").addEventListener("submit",saveQuestion);$("pack-form").addEventListener("submit",savePackInfo);
    $("stage-clear").addEventListener("click",()=>clearStageForm(true));$("question-clear").addEventListener("click",clearQuestionForm);$("new-pack").addEventListener("click",newPack);
    $("stage-preview").addEventListener("click",()=>previewStage(editingStage));$("preview-nav").addEventListener("click",()=>previewStage(editingStage));
    $("import-file").addEventListener("change",importFile);$("export-pack").addEventListener("click",exportPack);$("copy-json").addEventListener("click",copyJSON);$("copy-share-link").addEventListener("click",copyShareLink);
    $("save-template").addEventListener("click",saveTemplate);$("clear-template").addEventListener("click",()=>templateBoard.clear());$("template-label").addEventListener("input",updateTemplateCount);
    document.querySelectorAll("#question-form input,#question-form select").forEach(input=>input.addEventListener("input",previewQuestion));
  }
  function init(){loadSharedPack();bind();renderAll();previewQuestion();initTemplateBoard();persist("บันทึกในเครื่องแล้ว");}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();
